services:
  ubuntu-geth:
    build:
      context: ./docker/merge/
      dockerfile: Dockerfile
    restart: always
    command: bash -c "chmod +x ./start.sh && ./start.sh"
    environment:
      - STATIC_NODES_ARRAY=${STATIC_NODES_ARRAY}
      - CHAIN_ID=${CHAIN_ID}
      - NODE_PORT=${NODE_PORT}
      - IS_VALIDATOR_NODE=${IS_VALIDATOR_NODE}
      - SYNC_MODE=${SYNC_MODE}
      - SYNC_GCMODE=${SYNC_GCMODE}
      - NODE_HTTP_PORT=${NODE_HTTP_PORT}
      - NODE_WS_PORT=${NODE_WS_PORT}
      - BLOCKCHAIN_ENVIRONMENT=${BLOCKCHAIN_ENVIRONMENT}
      - ACCOUNT_FILE_CONTENT=${ACCOUNT_FILE_CONTENT}
      - WALLET_ACCOUNT=${WALLET_ACCOUNT}
      - PASSWORD_NODE=${PASSWORD_NODE}
      - GIT_COMMIT_HASH_GETH=${GIT_COMMIT_HASH_GETH}
      - STATS_SERVER=${STATS_SERVER}
      - STATS_NODE_USER=${STATS_NODE_USER}
      - STATS_NODE_PASSWORD=${STATS_NODE_PASSWORD}
    ports:
      - 30303:30303
      - 8545:8545
      - 8546:8546
    volumes:
      - ./data-blockchain:/blockchain
      - ./utils:/utils
    logging: # custom log max size and files
      driver: "json-file"
      options:
        max-size: "1k"
        max-file: "3"
