version: '3.8'

# networks:
#   blockchain:
#     driver: bridge

services:
  # stats:
  #   build:
  #     context: ./docker/stats/
  #     dockerfile: Dockerfile
  #   environment:
  #     - WS_SECRET=${WS_SECRET}
  #     - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
  #     - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
  #     - AWS_REGION=${AWS_REGION}
  #   ports:
  #     - 3000:3000
  #   networks:
  #     - blockchain

  validator:
    build:
      context: ./docker/validador/
      dockerfile: Dockerfile
    restart: always
    command: bash -c "chmod +x ./start.sh && ./start.sh"
    environment:
      - STATIC_NODES_ARRAY=${STATIC_NODES_ARRAY}
      - CHAIN_ID=${CHAIN_ID}
      - NODEPORT=${NODEPORT}
      - TYPE_BLOCKCHAIN=${TYPE_BLOCKCHAIN}
      - NODE_HTTP_PORT=${NODE_HTTP_PORT}
      - NODE_WS_PORT=${NODE_WS_PORT}
      - BLOCKCHAIN_ENVIRONMENT=${BLOCKCHAIN_ENVIRONMENT}
      - ACCOUNT_FILE_CONTENT=${ACCOUNT_FILE_CONTENT}
      - WALLET_ACCOUNT=${WALLET_ACCOUNT}
      - PASSWORD_NODE=${PASSWORD_NODE}
      - GIT_COMMIT_HASH=${GIT_COMMIT_HASH}
      - STATS_SERVER=${STATS_SERVER}
      - STATS_NODE_USER=${STATS_NODE_USER}
      - STATS_NODE_PASSWORD=${STATS_NODE_PASSWORD}
    ports:
      - 30303:30303
      - 8545:8545
      - 8546:8546
    # depends_on:
    #   - stats
    volumes:
      - ./data-blockchain:/blockchain
    # networks:
    #   - blockchain
